// frontend/mobile/src/components/LoginForm.tsx
/**
 * BLOCK_MOBILE_LOGIN_FORM_001
 * Purpose: Mobile viewport authentication screen using React Native Reusables styling.
 * Viewports: Handheld mobile devices with safe-area insets and 44px touch targets.
 */

import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { apiClient } from '@campus/api-client';

interface LoginFormProps {
  onSuccess: (tokens: { access_token: string; refresh_token: string }) => void;
}

export function MobileLoginForm({ onSuccess }: LoginFormProps) {
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const [mfaCode, setMfaCode] = useState('');
  const [isMfaStep, setIsMfaStep] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleLogin = async () => {
    if (!identifier || !password) {
      Alert.alert('Validation Error', 'Please enter both your identifier and password.');
      return;
    }

    setLoading(true);
    try {
      const res = await apiClient.post('/auth/login', {
        tenant_id: 'tenant_default',
        identifier,
        password,
        mfa_code: isMfaStep ? mfaCode : undefined,
      });

      if (res.requires_mfa) {
        setIsMfaStep(true);
      } else if (res.tokens) {
        onSuccess(res.tokens);
      }
    } catch (err: any) {
      Alert.alert('Login Failed', err.detail || err.message || 'Authentication error.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View className="w-full px-6 py-8 bg-white rounded-2xl border border-slate-200">
      <Text className="text-2xl font-bold text-slate-900 text-center mb-1">
        {isMfaStep ? 'Two-Factor Verification' : 'Campus Sign In'}
      </Text>
      <Text className="text-sm text-slate-500 text-center mb-6">
        {isMfaStep ? 'Enter your 6-digit TOTP code' : 'Access your courses, hostel & services'}
      </Text>

      {!isMfaStep ? (
        <>
          <View className="mb-4">
            <Text className="text-xs font-semibold uppercase text-slate-700 mb-1.5">Identifier</Text>
            <TextInput
              className="h-12 px-4 rounded-xl border border-slate-300 text-slate-900 text-base"
              placeholder="Email or Username"
              autoCapitalize="none"
              value={identifier}
              onChangeText={setIdentifier}
            />
          </View>

          <View className="mb-6">
            <Text className="text-xs font-semibold uppercase text-slate-700 mb-1.5">Password</Text>
            <TextInput
              className="h-12 px-4 rounded-xl border border-slate-300 text-slate-900 text-base"
              placeholder="••••••••••••"
              secureTextEntry
              value={password}
              onChangeText={setPassword}
            />
          </View>
        </>
      ) : (
        <View className="mb-6">
          <Text className="text-xs font-semibold uppercase text-slate-700 mb-1.5">TOTP Code</Text>
          <TextInput
            className="h-14 text-center font-mono text-2xl tracking-widest rounded-xl border border-slate-300 text-slate-900"
            placeholder="123456"
            keyboardType="number-pad"
            maxLength={6}
            value={mfaCode}
            onChangeText={setMfaCode}
          />
        </View>
      )}

      <TouchableOpacity
        className="h-12 bg-slate-900 rounded-xl items-center justify-center min-h-[44px]"
        onPress={handleLogin}
        disabled={loading}
      >
        {loading ? (
          <ActivityIndicator color="#ffffff" />
        ) : (
          <Text className="text-white font-semibold text-base">
            {isMfaStep ? 'Verify Code' : 'Sign In'}
          </Text>
        )}
      </TouchableOpacity>
    </View>
  );
}

// frontend/web/src/lib/components/auth/LoginForm.svelte
<script lang="ts">
  /**
   * BLOCK_WEB_LOGIN_FORM_001
   * Purpose: Viewport-resilient authentication form with TOTP step and error handling.
   * Viewports: 280px to 4K responsive scaling.
   */
  import { authState } from '$lib/auth-state.svelte';

  let { onSuccess = () => {} }: { onSuccess?: () => void } = $props();

  let tenantId = $state('tenant_default');
  let identifier = $state('');
  let password = $state('');
  let mfaCode = $state('');
  let isMfaStep = $state(false);
  let localError = $state<string | null>(null);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    localError = null;

    try {
      const result = await authState.login(tenantId, identifier, password, isMfaStep ? mfaCode : undefined);
      if (result.requiresMFA) {
        isMfaStep = true;
      } else {
        onSuccess();
      }
    } catch (err: any) {
      localError = authState.errorMessage || 'Authentication failed. Please check your credentials.';
    }
  }
</script>

<div class="w-full max-w-[min(420px,100%)] mx-auto p-6 sm:p-8 rounded-xl border border-slate-200 bg-white shadow-sm">
  <div class="mb-6 text-center">
    <h1 class="text-2xl font-bold tracking-tight text-slate-900">
      {isMfaStep ? 'Two-Factor Authentication' : 'Campus Portal Sign In'}
    </h1>
    <p class="text-sm text-slate-500 mt-1">
      {isMfaStep ? 'Enter the 6-digit code from your authenticator app' : 'Enter your institutional email or username'}
    </p>
  </div>

  {#if localError}
    <div class="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700 font-medium">
      {localError}
    </div>
  {/if}

  <form onsubmit={handleSubmit} class="space-y-4">
    {#if !isMfaStep}
      <div>
        <label for="identifier" class="block text-xs font-semibold uppercase tracking-wider text-slate-700 mb-1">
          Email or Username
        </label>
        <input
          id="identifier"
          type="text"
          bind:value={identifier}
          required
          placeholder="student@campus.edu or username"
          class="w-full h-11 px-3.5 rounded-lg border border-slate-300 text-slate-900 placeholder-slate-400 text-sm focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent transition"
        />
      </div>

      <div>
        <div class="flex items-center justify-between mb-1">
          <label for="password" class="block text-xs font-semibold uppercase tracking-wider text-slate-700">
            Password
          </label>
          <a href="/forgot-password" class="text-xs text-blue-600 hover:underline">Forgot password?</a>
        </div>
        <input
          id="password"
          type="password"
          bind:value={password}
          required
          placeholder="••••••••••••"
          class="w-full h-11 px-3.5 rounded-lg border border-slate-300 text-slate-900 placeholder-slate-400 text-sm focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent transition"
        />
      </div>
    {:else}
      <div>
        <label for="mfaCode" class="block text-xs font-semibold uppercase tracking-wider text-slate-700 mb-1">
          TOTP Passcode
        </label>
        <input
          id="mfaCode"
          type="text"
          inputmode="numeric"
          maxlength="6"
          bind:value={mfaCode}
          required
          placeholder="123456"
          class="w-full h-12 text-center tracking-[0.5em] font-mono text-xl rounded-lg border border-slate-300 text-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-900 focus:border-transparent transition"
        />
      </div>
    {/if}

    <button
      type="submit"
      disabled={authState.isLoading}
      class="w-full h-11 bg-slate-900 hover:bg-slate-800 active:bg-slate-950 text-white font-medium text-sm rounded-lg transition duration-150 flex items-center justify-center disabled:opacity-50 min-h-[44px]"
    >
      {#if authState.isLoading}
        <span class="animate-spin mr-2">⟳</span> Authenticating...
      {:else}
        {isMfaStep ? 'Verify & Continue' : 'Sign In to Campus'}
      {/if}
    </button>
  </form>
</div>
